export const config = {
  id: 'ecommerce',
  label: 'E-commerce',
  tabs: [
    { id: 'full', label: 'Full' },
    { id: 'shop', label: 'Shop' },
  ],
  colorSchema: [
    {
      id: '--cf-logo',
      label: 'Logo',
      group: 'Brand',
      semantic: 'brand',
      weightHint: 'Logo mark color',
      skipSuggestions: true,
      optional: false,
      contrastAgainst: null,
    },
    {
      id: '--cf-primary',
      label: 'Primary',
      group: 'Brand',
      semantic: 'brand',
      weightHint: 'Dominant · nav bar, footer',
      skipSuggestions: false,
      optional: false,
      contrastAgainst: null,
    },
    {
      id: '--cf-accent',
      label: 'Accent',
      group: 'Brand',
      semantic: 'brand',
      weightHint: 'CTA buttons, sale badges',
      skipSuggestions: false,
      optional: false,
      contrastAgainst: null,
    },
    {
      id: '--cf-bg',
      label: 'Background',
      group: 'Neutrals',
      semantic: 'neutral',
      weightHint: 'Page background',
      skipSuggestions: false,
      optional: false,
      contrastAgainst: null,
    },
    {
      id: '--cf-surface',
      label: 'Surface',
      group: 'Neutrals',
      semantic: 'neutral',
      weightHint: 'Product cards',
      skipSuggestions: false,
      optional: false,
      contrastAgainst: null,
    },
    {
      id: '--cf-filter-bg',
      label: 'Filter Panel',
      group: 'Neutrals',
      semantic: 'neutral',
      weightHint: 'Left sidebar background',
      skipSuggestions: false,
      optional: true,
      contrastAgainst: null,
    },
    {
      id: '--cf-text',
      label: 'Body Text',
      group: 'Neutrals',
      semantic: 'neutral',
      weightHint: 'Primary text',
      skipSuggestions: false,
      optional: false,
      contrastAgainst: null,
    },
    {
      id: '--cf-text-muted',
      label: 'Muted Text',
      group: 'Neutrals',
      semantic: 'neutral',
      weightHint: 'Prices, metadata',
      skipSuggestions: false,
      optional: false,
      contrastAgainst: null,
    },
  ],
  defaults: {
    '--cf-logo': '#ffffff',
    '--cf-primary': '#1e3a5f',
    '--cf-accent': '#2e619e',
    '--cf-bg': '#0a0e14',
    '--cf-surface': '#141b27',
    '--cf-filter-bg': '#111827',
    '--cf-text': '#f3f4f6',
    '--cf-text-muted': '#9ca3af',
  },
  defaultMode: 'dark',
  neutralDefaults: {
    light: {
      '--cf-bg': '#f9fafb',
      '--cf-surface': '#ffffff',
      '--cf-filter-bg': '#f3f4f6',
      '--cf-text': '#111827',
      '--cf-text-muted': '#6b7280',
    },
    dark: {
      '--cf-bg': '#0a0e14',
      '--cf-surface': '#141b27',
      '--cf-filter-bg': '#111827',
      '--cf-text': '#f3f4f6',
      '--cf-text-muted': '#9ca3af',
    },
  },
}
