export const config = {
  id: 'landing',
  label: 'Landing Page',
  tabs: [
    { id: 'full', label: 'Full' },
    { id: 'hero', label: 'Hero' },
    { id: 'features', label: 'Features' },
  ],
  colorSchema: [
    {
      id: '--cf-logo',
      label: 'Logo',
      group: 'Brand',
      semantic: 'brand',
      weightHint: 'Logo mark color',
      skipSuggestions: true,
      optional: false,
      contrastAgainst: null,
    },
    {
      id: '--cf-primary',
      label: 'Primary',
      group: 'Brand',
      semantic: 'brand',
      weightHint: 'Dominant · nav, hero, footer',
      skipSuggestions: false,
      optional: false,
      contrastAgainst: null,
    },
    {
      id: '--cf-secondary',
      label: 'Secondary',
      group: 'Brand',
      semantic: 'brand',
      weightHint: 'Supporting · hero gradient, icons',
      skipSuggestions: false,
      optional: false,
      contrastAgainst: null,
    },
    {
      id: '--cf-accent',
      label: 'Accent / CTA',
      group: 'Brand',
      semantic: 'brand',
      weightHint: 'Call-to-action buttons',
      skipSuggestions: false,
      optional: false,
      contrastAgainst: null,
    },
    {
      id: '--cf-bg',
      label: 'Background',
      group: 'Neutrals',
      semantic: 'neutral',
      weightHint: 'Page background',
      skipSuggestions: false,
      optional: false,
      contrastAgainst: null,
    },
    {
      id: '--cf-surface',
      label: 'Surface',
      group: 'Neutrals',
      semantic: 'neutral',
      weightHint: 'Cards & section fills',
      skipSuggestions: false,
      optional: false,
      contrastAgainst: null,
    },
    {
      id: '--cf-text',
      label: 'Body Text',
      group: 'Neutrals',
      semantic: 'neutral',
      weightHint: 'Primary text',
      skipSuggestions: false,
      optional: false,
      contrastAgainst: null,
    },
    {
      id: '--cf-text-muted',
      label: 'Muted Text',
      group: 'Neutrals',
      semantic: 'neutral',
      weightHint: 'Secondary / helper text',
      skipSuggestions: false,
      optional: false,
      contrastAgainst: null,
    },
  ],
  defaults: {
    '--cf-logo': '#ffffff',
    '--cf-primary': '#1d2965',
    '--cf-secondary': '#3781ca',
    '--cf-accent': '#f17c1d',
    '--cf-bg': '#1a1e40',
    '--cf-surface': '#0f1533',
    '--cf-text': '#d8e4fe',
    '--cf-text-muted': '#6f91ea',
  },
  defaultMode: 'dark',
  neutralDefaults: {
    light: {
      '--cf-bg': '#ffffff',
      '--cf-surface': '#f0f4ff',
      '--cf-text': '#0d1340',
      '--cf-text-muted': '#5a6fa8',
    },
    dark: {
      '--cf-bg': '#1a1e40',
      '--cf-surface': '#0f1533',
      '--cf-text': '#d8e4fe',
      '--cf-text-muted': '#6f91ea',
    },
  },
}
